package com.lide.core.model;

import java.nio.file.Path;
import java.util.List;

/**
 * Represents the canonical JSON structure emitted for each analyzed JSP.
 * <p>
 * The structure mirrors the generated JSON payloads:
 * <pre>{
 *   "pageId": "relative/path/to/page.jsp",
 *   "title": "Optional human-friendly title if derivable",
 *   "forms": [ ... ],
 *   "outputs": [ ... ],
 *   "metadata": {
 *     "controllerCandidates": ["com.lide.app.CustomerAction"],
 *     "notes": ["Generated by static analysis; may need human review."]
 *   }
 * }
 * </pre>
 * Implementations will populate these fields during future phases.
 * </p>
 */
public class PageDescriptor {

    private Path sourcePath; // TODO: determine desired representation of page identity
    private String pageId; // TODO: set relative identifier
    private String title; // TODO: infer title from page content or metadata
    private List<FormDescriptor> forms; // TODO: capture form descriptors discovered in the page
    private List<OutputSectionDescriptor> outputs; // TODO: capture output structures such as tables
    private List<NavigationTarget> navigationTargets; // TODO: capture navigation targets to other JSPs
    private List<String> controllerCandidates; // TODO: correlate JSP with backing Java classes
    private List<String> backingBeanCandidates; // TODO: proposed backing beans inferred from heuristics
    private List<String> notes; // TODO: include diagnostic notes for reviewers
    private Double confidenceScore; // TODO: compute a confidence indicator once metadata is merged
    private String confidenceLabel; // TODO: expose HIGH/MEDIUM/LOW interpretation for dashboards

    public PageDescriptor() {
        // Default constructor for frameworks and serialization.
    }

    public Path getSourcePath() {
        return sourcePath;
    }

    public void setSourcePath(Path sourcePath) {
        this.sourcePath = sourcePath;
    }

    public String getPageId() {
        return pageId;
    }

    public void setPageId(String pageId) {
        this.pageId = pageId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<FormDescriptor> getForms() {
        return forms;
    }

    public void setForms(List<FormDescriptor> forms) {
        this.forms = forms;
    }

    public List<OutputSectionDescriptor> getOutputs() {
        return outputs;
    }

    public void setOutputs(List<OutputSectionDescriptor> outputs) {
        this.outputs = outputs;
    }

    public List<NavigationTarget> getNavigationTargets() {
        return navigationTargets;
    }

    public void setNavigationTargets(List<NavigationTarget> navigationTargets) {
        this.navigationTargets = navigationTargets;
    }

    public List<String> getControllerCandidates() {
        return controllerCandidates;
    }

    public void setControllerCandidates(List<String> controllerCandidates) {
        this.controllerCandidates = controllerCandidates;
    }

    public List<String> getNotes() {
        return notes;
    }

    public void setNotes(List<String> notes) {
        this.notes = notes;
    }

    public Double getConfidenceScore() {
        return confidenceScore;
    }

    public void setConfidenceScore(Double confidenceScore) {
        this.confidenceScore = confidenceScore;
    }

    public List<String> getBackingBeanCandidates() {
        return backingBeanCandidates;
    }

    public void setBackingBeanCandidates(List<String> backingBeanCandidates) {
        this.backingBeanCandidates = backingBeanCandidates;
    }

    public String getConfidenceLabel() {
        return confidenceLabel;
    }

    public void setConfidenceLabel(String confidenceLabel) {
        this.confidenceLabel = confidenceLabel;
    }
}
